/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Profile: () => import('#controllers/profile_controller'),
  Session: () => import('#controllers/session_controller'),
  Signup: () => import('#controllers/signup_controller'),
  Timesheets: () => import('#controllers/timesheets_controller'),
}
